fecha: "2022-07-14"
safe_dir: "/app/data/Copernicus/"
snap_dir: "/app/data/processed/"
model_dir: "/app/models/models/"
pred_dir: "/app/data/preds/"
map_dir: "/app/data/Chl_Maps/"
available_dates_dir: "/app/data/dates/"
geojson_file: "/app/fetch/marmenor_polygon.geojson"
colormap_file: "/app/fetch/colormap_custom.txt"
profundidades: [0_1, 1_2, 2_3, 3_4]
generate_gif: true
plot_individuales: true
tile: "T30TXQ"
area_of_interest: [-1.349258,44.519031,-0.956497,44.79012,]
config_dates: [
    "2015-08-18",
    "2015-11-26",
    "2016-05-24",
    "2016-07-23",
    "2016-08-12",
    "2016-09-01",
    "2016-09-21",
    "2016-10-21",
    "2017-04-09",
    "2017-04-19",
    "2017-04-24",
    "2017-05-04",
    "2017-05-19",
    "2017-05-24",
    "2017-07-03",
    "2017-07-18",
    "2017-07-28",
    "2017-08-02",
    "2017-10-06",
    "2017-10-11",
    "2017-10-26",
    "2018-01-24",
    "2018-04-24",
    "2018-06-13",
    "2018-06-28",
    "2018-07-13",
    "2018-07-23",
    "2018-08-27",
    "2018-10-16",
    "2018-11-15",
    "2018-11-30",
    "2018-12-30",
    "2019-01-24",
    "2019-02-28",
    "2019-03-05",
    "2019-03-20",
    "2019-04-04",
    "2019-05-14",]

batch_template:
    graph_xml: "/app/fetch/snap_graph_application.xml"
    template_params: "/app/fetch/snap_graph_application.properties"
    gpt_bin: "/opt/snap/bin/gpt"
    output_format: "tif"
    netSet: "C2X-COMPLEX-Nets"
    output_format: "GeoTIFF"
    resampleResolution: 10
    geoRegion: POLYGON((-1.349258 44.519031,-1.349258 44.79012,-0.956497 44.79012,-0.956497 44.519031,-1.349258 44.519031))
    salinity: 42
    temperature: 20
    netSet: C2X-COMPLEX-Nets
    outputRtoa: true
    outputAcReflectance: true
    outputRhown: true
    bandSubset: rtoa_B1,rtoa_B2,rtoa_B3,rtoa_B4,rtoa_B5,rtoa_B6,rtoa_B7,rtoa_B8,rtoa_B8A,rtoa_B9,rtoa_B10,rtoa_B11,rtoa_B12,rhow_B1,rhow_B2,rhow_B3,rhow_B4,rhow_B5,rhow_B6,rhow_B7,rhow_B8A,rhown_B1,rhown_B2,rhown_B3,rhown_B4,rhown_B5,rhown_B6,conc_chl,c2rcc_flags
