fecha: "2022-07-14"
safe_dir: "/app/data/Copernicus/"
snap_dir: "/app/data/processed/"
model_dir: "/app/models/models/"
pred_dir: "/app/data/preds/"
map_dir: "/app/data/Chl_Maps/"
available_dates_dir: "/app/data/dates/"
geojson_file: "/app/fetch/marmenor_polygon.geojson"
colormap_file: "/app/fetch/colormap_custom.txt"
profundidades: [0_1, 1_2, 2_3, 3_4]
generate_gif: true
plot_individuales: true
tile: "T30TXQ"
area_of_interest: [-1.349258,44.519031,-0.956497,44.79012,]

config_dates: [
"2017-04-24",
"2017-05-04",
"2017-05-19",
"2017-08-17",
"2018-04-24",
"2018-06-28",
"2018-07-23",
"2018-08-27",
"2018-10-16",
"2018-11-15",
"2019-02-28",
"2019-04-04",
"2019-09-16",
"2019-10-21",
"2019-12-05",
"2020-02-03",
"2020-09-10",
"2020-10-15",
"2021-12-14",
"2022-06-07",
"2022-09-05",
"2023-02-07",
"2023-07-27",
"2023-09-25",
"2024-03-13",
"2024-05-02",
"2024-06-06",
"2024-11-08",
    ]
